controllers/BalanceController.php
<?php

namespace app\controllers;

use app\models\OrderPositions;
use app\models\Orders;
use app\models\UserBalance;
use app\models\UserBalanceLog;
use app\models\Users;
use Yii;
use yii\data\ActiveDataProvider;
use yii\helpers\ArrayHelper;

class BalanceController extends \yii\web\Controller
{
    public function beforeAction($action) {

        if (Yii::$app->user->isGuest || (int)Yii::$app->user->id <= 0) {
            Yii::$app->user->loginRequired();
            return false;
        }
        return true;
    }

    public function actionIndex()
    {
        $balanceQuery = UserBalanceLog::find()
            ->andWhere(['user_id' =>\Yii::$app->user->id])
            ->orderBy('created_at DESC')
        ;

        $balanceProvider = new ActiveDataProvider(
            [
                'query' => $balanceQuery,
                'pagination' => [
                    'pageSize' => 10
                ],
                'sort' => false,
            ]
        );

        return $this->render('index', ['balanceProvider' => $balanceProvider]);
    }

    public function actionDeposite() {

        if (!Yii::$app->user->identity->isAdmin()) {
            Yii::$app->response->redirect(['balance/index']);
        }

        //PositionsUpdate
        if (Yii::$app->request->isPost) {
            $userBalanceLog = new UserBalanceLog();
            $userBalanceLog->load(Yii::$app->request->post());
            UserBalance::changeBalance(
                $userBalanceLog->sum,
                $userBalanceLog->user_id,
                $userBalanceLog->order_id,
                UserBalance::TYPE_DEPOSIT,
                $userBalanceLog->comment
            );
        }

        return $this->render('deposite', [
            'users' => $this->getAllActiveUsers(),
            'orders' => $this->getAllOrders(),
            'balanceList' => $this->getAllBalance(),
            'model'=> new UserBalanceLog()
        ]);
    }

    public function actionDonate() {

        if (Yii::$app->request->isPost) {
            $userBalanceLog = new UserBalanceLog();
            $userBalanceLog->load(Yii::$app->request->post());
            UserBalance::changeBalance(
                $userBalanceLog->sum,
                \Yii::$app->user->id,
                0,
                UserBalance::TYPE_DONATE
            );
            UserBalance::changeBalance(
                $userBalanceLog->sum,
                1,
                0,
                UserBalance::TYPE_DEPOSIT,
                'Вам пожертвование от '.Yii::$app->user->identity->username
            );
        }

        return $this->render('donate', [
            'model'=> new UserBalanceLog()
        ]);
    }

    // TODO функция в разработке
    public function actionRefreshBalance() {

        if (!Yii::$app->user->identity->isAdmin()) {
            Yii::$app->response->redirect(['balance/index']);
        }

        //PositionsUpdate
        if (Yii::$app->request->isPost) {
            $userBalanceLog = new UserBalanceLog();
            $userBalanceLog->load(Yii::$app->request->post());

        }
    }

    protected function getAllActiveUsers() {

        $userList = Users::find()->active()->addSelect(['id', 'username'])->all();
        return ArrayHelper::map($userList,'id','username');
    }

    protected function getAllOrders() {

        $orderList = Orders::find()
            ->addSelect(['id as value', 'id as label' ])
            ->orderBy('created_at DESC')
            ->asArray()
            ->all();

        return $orderList;
    }

    protected function getAllBalance() {
        return ArrayHelper::map(
            UserBalance::find()
                ->addSelect(['user_id', 'balance'])
                ->innerJoinWith(['user' => function($query) {
                    $query->andWhere(['users.active' => Users::STATUS_ACTIVE]);
                }])
                ->orderBy('balance ASC')
                ->all(),
            'user_id',
            'balance'
        );
    }

}

controllers/CatalogController.php
<?php

namespace app\controllers;

use app\models\catalog\CatalogCategory;
use app\models\Orders;
use app\models\OrdersUsers;

class CatalogController extends \yii\web\Controller
{
    public function beforeAction($action)
    {

        if (\Yii::$app->user->isGuest || (int)\Yii::$app->user->id <= 0) {
            \Yii::$app->user->loginRequired();
        }
        return true;
    }

    public function actionIndex()
    {
        $categories = CatalogCategory::getKdvCategories();
        return $this->render('index', ['categories' => $categories]);
    }

    public function actionItems($categoryUrl) {

        $order = Orders::findActiveOrder();

        $category = CatalogCategory::find()
            ->andWhere('url = "/catalog/'.$categoryUrl.'"')
            ->addSelect(['kdv_id','name'])
            ->one();
        $items = CatalogCategory::getItems($category->kdv_id);

        return $this->render('items', [
            'items' => $items,
            'catalogName' => $category->name,
            'order' => $order
        ]);
    }

    public function actionGenerateGroupKdv() {
        CatalogCategory::getKdvCategories(true);
    }


}

views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use app\widgets\Alert;
use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?php $this->registerCsrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
    <?php
    NavBar::begin([
        'brandLabel' => Yii::$app->name,
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar-inverse navbar-fixed-top navbar-collapse',
        ],
    ]);

    if (!Yii::$app->user->isGuest) {
        $leftItems[] = '<li>'.\app\models\UserBalance::getBalanceHtml(). '</li>';
        $leftItems[] = [
            'label' => 'Donate',
            'url' => ['balance/donate'],
            'linkOptions' => ['style' => 'background-color: #fcf8e3; color: #777;']
        ];
        echo Nav::widget([
            'options' => ['class' => 'navbar-nav navbar-left'],
            'items' => $leftItems
        ]);
    }


    $items = [
            ['label' => 'Авторизоваться', 'url' => ['/site/login']],
            ['label' => 'Зарегистрироваться', 'url' => ['/site/signup']]
    ];
    if (!Yii::$app->user->isGuest) {
        $items = [

            ['label' => 'Каталог', 'url' => ['/catalog/index']],
            ['label' => 'Список заказов', 'url' => ['/orders/list']],
            ['label' => 'Финансы', 'url' => ['/balance/index']],
            ['label' => 'Доска почёта', 'url' => ['/statistics/index']],
            '<li>'
                . Html::beginForm(['/site/logout'], 'post')
                . Html::submitButton(
                    'Выйти (<span id="username" data-id="'.Yii::$app->user->id.'">' . Yii::$app->user->identity->username . '</span>)',
                    ['class' => 'btn btn-link logout']
                )
                . Html::endForm()
                . '</li>',
            '<li><a href="#" id="subscribe" class="glyphicon glyphicon-envelope" style="color: white;" title="Подписаться на уведомления"></a></li>'
        ];
    }
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        'items' => $items,
    ]);
    NavBar::end();
    ?>

    <div class="container">
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= Alert::widget() ?>
        <?= $content ?>
    </div>

</div>

<?php
    $this->endBody();
    $this->registerJsFile('//www.gstatic.com/firebasejs/3.6.8/firebase.js');
    $this->registerJsFile('/firebase_subscribe.js');
?>
<script type="text/javascript">
    var reformalOptions = {
        project_id: 983757,
        project_host: "tradesoft-kdv.reformal.ru",
        tab_orientation: "bottom-right",
        tab_indent: "10px",
        tab_bg_color: "#F05A00",
        tab_border_color: "#FFFFFF",
        tab_image_url: "http://tab.reformal.ru/T9GC0LfRi9Cy0Ysg0Lgg0L%252FRgNC10LTQu9C%252B0LbQtdC90LjRjw==/FFFFFF/07330bc5004dd1d3a4e80c777f77d3dc/bottom-right/0/tab.png",
        tab_border_width: 0
    };

    (function() {
        var script = document.createElement('script');
        script.type = 'text/javascript'; script.async = true;
        script.src = ('https:' == document.location.protocol ? 'https://' : 'http://') + 'media.reformal.ru/widgets/v3/reformal.js';
        document.getElementsByTagName('head')[0].appendChild(script);
    })();
</script><noscript><a href="http://reformal.ru"><img src="http://media.reformal.ru/reformal.png" /></a><a href="http://tradesoft-kdv.reformal.ru">Oтзывы и предложения для КДВ</a></noscript>
</body>
</html>
<?php $this->endPage();
?>