models/Orders.php
<?php

namespace app\models;

use app\models\query\OrdersQuery;
use yii\behaviors\TimestampBehavior;
use yii\db\ActiveRecord;

/**
 * This is the model class for table "orders".
 *
 * @property int $id
 * @property string $status
 * @property int $created_at
 * @property int $updated_at
 *
 * @property OrderPositions[] $orderPositions
 * @property OrdersUsers[] $ordersUsers
 */
class Orders extends \yii\db\ActiveRecord
{
    const STATUS_NOT_ACTIVE = 1; // не активен
    const STATUS_ACTIVE = 2; // открыт для заказа
    const STATUS_BLOCK = 3; // заказ заблокирован
    const STATUS_BASKET = 4; // корзина
    const STATUS_PAYED = 5; // закрыт и списаны деньги с баланса

    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'orders';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['status'], 'required'],
            [['created_at', 'updated_at', 'status'], 'integer'],
        ];
    }

    public function behaviors(){
        return [
            [
                'class' => TimestampBehavior::class,
                'attributes' => [
                    ActiveRecord::EVENT_BEFORE_INSERT => ['created_at', 'updated_at'],
                    ActiveRecord::EVENT_BEFORE_UPDATE => ['updated_at'],
                ],
            ],
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getOrderPositions()
    {
        return $this->hasMany(OrderPositions::className(), ['order_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getOrdersUsers()
    {
        return $this->hasMany(OrdersUsers::className(), ['order_id' => 'id']);
    }

    /**
     * @return OrdersQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new OrdersQuery(get_called_class());
    }

    /**
     * @param int $id
     * @return Orders|null
     */
    public static function findIdentity($id)
    {
        return static::find()
            ->active()
            ->andWhere(['id' => $id])
            ->one();
    }

    /**
     * @return Orders|null
     */
    public static function findActiveOrder() {

        return static::find()
            ->andWhere(['status' => Orders::STATUS_ACTIVE])
            ->orderBy('created_at ASC')
            ->one();
    }

    /**
     * @return bool
     */
    public function isTodayOrder() {

        $today = strtotime(date('d.m.Y'));
        $tomorrow  = mktime(0, 0, 0, date('m')  , date('d')+1, date('Y'));

        return $this->created_at >= $today && $this->created_at < $tomorrow;
    }

    /**
     * @return bool
     */
    public function isProcessing() {

        return OrdersUsers::find()->andWhere(['order_id' => $this->id, 'status' => OrdersUsers::STATUS_START])->count() > 0;
    }

    /**
     * @return OrdersUsers[]|array
     */
    public function whoIsProcessing() {
        return OrdersUsers::find()->andWhere(['order_id' => $this->id, 'status' => OrdersUsers::STATUS_START])->all();
    }

    /**
     * @return array
     */
    public static function statusDone() {
        return [self::STATUS_BLOCK, self::STATUS_PAYED];
    }
}

controllers/OrdersController.php
<?php

namespace app\controllers;

use app\models\kdv\KdvBasket;
use app\models\Notification;
use app\models\OrderPositions;
use app\models\OrderPositionsSearch;
use app\models\Orders;
use app\models\OrdersUsers;
use app\models\Statistic;
use app\models\UserBalance;
use app\models\UserBalanceLog;
use app\models\Users;
use Yii;
use yii\data\ActiveDataProvider;
use yii\data\ArrayDataProvider;

class OrdersController extends \yii\web\Controller
{

    public function beforeAction($action)
    {

        if (Yii::$app->user->isGuest || (int)Yii::$app->user->id <= 0) {
            Yii::$app->user->loginRequired();
            return false;
        }
        return true;
    }
    public function actionAdd()
    {
        $todayOrder = Orders::findActiveOrder();
        if (!$todayOrder) {
            $order = new Orders();
            $order->status = Orders::STATUS_ACTIVE;
            if ($order->save()) {
                $todayOrder = $order;

                $kdvBasket = new KdvBasket();
                $kdvBasket->clearBasket();

                $notification = new Notification();
                $notification->title = 'Новый заказ!';
                $notification->body = 'Для перехода к заказу нажмите на данное сообщение';
                $notification->clickAction = 'https://' . $_SERVER['HTTP_HOST'].
                    \yii\helpers\Url::to(['orders/view', 'id' => $todayOrder->id]);
                $notification->send();
            }
        }

        Yii::$app->response->redirect(['orders/view', 'id' => $todayOrder->id]);
    }

    public function actionDelete($id)
    {
        $order = Orders::findIdentity($id);
        $order->status = Orders::STATUS_NOT_ACTIVE;
        $order->save();

        Yii::$app->response->redirect(['orders/list']);
    }

    public function actionView($id)
    {
        $ordersUsers = new OrdersUsers();

        if (Yii::$app->request->isPost) {
            $post = Yii::$app->request->post();
            $postKeys = array_keys($post);

            foreach ($postKeys as $typeUpdate) {
                switch ($typeUpdate) {
                    case 'OrderPositions':
                        $orderPosition = new OrderPositions();
                        $orderPosition->order_id = $id;
                        $orderPosition->user_id = Yii::$app->user->id;
                        if ($orderPosition->load($post)) {
                            $orderPosition->addPosition();
                        }
                        if ($post['ajax']) {
                            return
                                Yii::$app->session->getFlash('danger', null, true)?:
                                    Yii::$app->session->getFlash('info', null, true)?:
                                        Yii::$app->session->getFlash('success', null, true);
                        }
                        break;
                    case 'OrdersUsers':
                        $findOrdersUsers = OrdersUsers::find()->andWhere([
                            'order_id' => $id,
                            'user_id' => Yii::$app->user->id
                        ])->one();
                        if (!$findOrdersUsers) {
                            $ordersUsers->order_id = $id;
                            $ordersUsers->user_id = Yii::$app->user->id;
                        } else {
                            $ordersUsers = $findOrdersUsers;
                        }
                        if ($ordersUsers->load(Yii::$app->request->post())) {

                            if (!$findOrdersUsers) {
                                $ordersUsers->insert();
                            } else {
                                $ordersUsers->update();
                            }
                        }
                        break;
                }
            }
        }

        $order = Orders::findIdentity($id);

        if (!$order) {
            Yii::$app->response->redirect(['orders/list']);
            return '';
        }

        $positionModel = new OrderPositions();

        if ($order->status == Orders::STATUS_ACTIVE) {

            $myOrdersUsers = OrdersUsers::find()->andWhere(['order_id' => $id, 'user_id' => Yii::$app->user->id])->addSelect(['status'])->one();

            if (!$myOrdersUsers) {
                $view = 'freeze';
                $ordersUsersStatus = 'new';
            }
            elseif ($myOrdersUsers->status == OrdersUsers::STATUS_DONE) {
                $view = 'freeze';
                $ordersUsersStatus = 'done';
            }
            else {
                $view = 'edit';
                $ordersUsersStatus = 'process';
            }

            $totalPositionsQuery = OrderPositions::find()
                ->andWhere(['order_id' => $id])
                ->groupBy('kdv_url')
                ->addSelect('order_id, kdv_url, price, kdv_price, caption, user_id, multiple')
                ->addSelect('SUM([[amount]]) AS amount')
                ->joinWith('user')
                ->addSelect(['GROUP_CONCAT(DISTINCT users.username,  :p1 , [[amount]],  :p2 SEPARATOR \', \') AS username'])
                ->addParams([':p1' => ' (', ':p2' => 'шт.)'])
                ->orderBy(['multiple' => SORT_DESC])
                ->asArray();
            ;

            $totalPositionProvider = new ArrayDataProvider(
                [
                    'allModels' => $totalPositionsQuery->all(),
                    'pagination' => [
                        'pageSize' => 100
                    ],
                    'sort' => false,
                ]
            );
        }
        elseif (in_array($order->status, Orders::statusDone())) {
            $view = 'view';
            $ordersUsersStatus = 'close';

            $searchModel = new OrderPositionsSearch();
            $viewTotalDataProvider = $searchModel->getTotalPositionProvider($id, Yii::$app->request->post());
        }
        else {
            return ''; // заказ не активен
        }

        $positionsQuery = OrderPositions::find()
            ->andWhere(['order_id' => $id,'user_id' => Yii::$app->user->id]);

        $dataProvider = new ActiveDataProvider(
            [
                'query' => $positionsQuery,
                'pagination' => [
                    'pageSize' => 100
                ],
                'sort' => false,
            ]
        );

        $users = [];
        $userList = OrderPositions::find()
            ->joinWith('user')
            ->select(['username', 'user_id'])
            ->andWhere(['order_id' =>  $id])
            ->asArray()->all();
        foreach ($userList as $user) {
            $users[$user['user_id']] = $user['username'];
        }

        $params = [
            'order' => $order,
            'users' => $users,
            'positionProvider' => $dataProvider,
            'positionModel' => $positionModel,
            'ordersUsersModel' => $ordersUsers,
            'ordersUsersStatus' => $ordersUsersStatus
        ];

        if ($order->status == Orders::STATUS_ACTIVE) {
            $params['totalPositionProvider'] = $totalPositionProvider;
            $params['topUsedPosition'] = Statistic::getTopUsedPosition(Yii::$app->user->id);
            $params['whoIsProcessing'] = $order->whoIsProcessing();
            $params['countUsers'] = OrdersUsers::find()->andWhere(['order_id' => $id])->count();
        }
        elseif (in_array($order->status, Orders::statusDone())) {
            $params['writeOffList'] = Statistic::topBalanceList('writeOff', $id);
            $params['countPositionsList'] = Statistic::topCountPositionsList($id);
            $params['weightList'] = Statistic::topWeightList($id);
            $params['viewTotalPositionsList'] = $viewTotalDataProvider;
            $params['searchModel'] = $searchModel;
        }

        return $this->render($view, $params);
    }

    public function actionList()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Orders::find()->active()->orderBy('created_at desc'),
            'pagination' => [
                'pageSize' => 20
            ],
        ]);
        return $this->render('list', ['dataProvider' => $dataProvider]);
    }

    public function actionBlock($id) {

        if (!Yii::$app->user->identity->isAdmin()) {
            Yii::$app->response->redirect(['order/list']);
        }

        $order = Orders::findIdentity($id);
        if ($order) {
            $order->status = Orders::STATUS_BLOCK;
            $order->update();

            $kdvBasket = new KdvBasket();
            $message = $kdvBasket->sincBasket($id);
            Yii::$app->session->setFlash('info', $message);

            $userList = [];
            $positions = $order->getOrderPositions()->all();
            if ($positions) {
                foreach ($positions as $position) {
                    $userList[] = $position->user_id;
                }

                // отправка уведомлений только тем кто участвует в заказе
                $notification = new Notification();
                $notification->title = 'Заказ №'.$id.' заблокирован';
                $notification->body = 'Изменения в заказе больше не принимаются!';
                $notification->clickAction = 'https://' . $_SERVER['HTTP_HOST'] .
                    \yii\helpers\Url::to(['balance/index']);
                $notification->send($userList);
            }
        }
        Yii::$app->response->redirect(['orders/list']);
    }
    public function actionPayOrder($id) {

        if (!Yii::$app->user->identity->isAdmin()) {
            Yii::$app->response->redirect(['order/list']);
        }

        UserBalance::payOrder($id);

        Yii::$app->response->redirect(['orders/list']);
    }

    public function actionOpen($id) {

        $order = Orders::findIdentity($id);
        if ($order && in_array($order->status, Orders::statusDone())) {

            if ($order->status === Orders::STATUS_PAYED) {

controllers/PositionsController.php
<?php

namespace app\controllers;

use app\models\OrderPositions;
use app\models\Orders;
use Yii;

class PositionsController extends \yii\web\Controller
{
    public function actionDelete($orderId, $id)
    {
        $order = Orders::findIdentity($orderId);
        $isAdmin = Yii::$app->user->identity->isAdmin();
        $orderStatusDone = $order && in_array($order->status, Orders::statusDone(), true);
        if ($order &&
            (
                $isAdmin ||
                !$orderStatusDone
            )
        ) {
            $filterList = [
                'id' => $id,
                'order_id' => $orderId,
            ];
            if (!$isAdmin) {
                $filterList['user_id'] = Yii::$app->user->id;
            }

            /** @var OrderPositions $position */
            $position = OrderPositions::find()->andWhere($filterList)->one();
            if ($position) {
                $position->deletePosition();
            }
        }
        elseif ($orderStatusDone) {
            Yii::$app->session->setFlash('danger', 'Удаление невозможно! Заказ заблокирован для изменений!');
        }

        Yii::$app->response->redirect(['orders/view', 'id' => $orderId]);
    }

}

controllers/StatisticsController.php
<?php

namespace app\controllers;

use app\models\OrderPositions;
use app\models\Orders;
use app\models\Statistic;
use app\models\UserBalance;
use app\models\Users;
use yii\data\ActiveDataProvider;

class StatisticsController extends \yii\web\Controller
{
    public function actionIndex()
    {
        $userList = Users::find()->select(['username', 'id'])->asArray()->all();
        foreach ($userList as $user) {
            $users[$user['id']] = $user['username'];
        }

        return $this->render('index',
            [
                'users' => $users,
                'writeOffList' => Statistic::topBalanceList('writeOff'),
                'countPositionsListByUser' => Statistic::topCountPositionsList(),
                'donateList' => Statistic::topBalanceList('donate'),
                'weightListByUser' => Statistic::topWeightList(),
                'weightListByOrder' => Statistic::getTopWeightOrder(),
                'countPositionsListByOrder' => Statistic::getTopCountPositions(),
                'totalPriceListByOrder' => Statistic::getTopTotalPriceOrder(),
                'countUsersListByOrder' => Statistic::getTopCountUsers(),
                'popularPositions' => Statistic::getPopularPositions(),
                'topAmountPositions' => Statistic::getTopAmountPositions()
            ]);
    }

    public function actionPersonal() {

        if (\Yii::$app->user->isGuest || (int)\Yii::$app->user->id <= 0) {
            \Yii::$app->response->redirect(['site/login']);
        }

        $orderListQuuery = OrderPositions::find()
            ->addSelect(
                [
                    'order_id',
                    'SUM(amount) as amount',
                    'SUM(price*amount) as price',
                    'SUM(weight*amount) as weight',
                    'SUM(protein*amount*weight/100) as protein',
                    'SUM(fat*amount*weight/100) as fat',
                    'SUM(carbon*amount*weight/100) as carbon',
                    'SUM(kcal*amount*weight/100) as kcal'
                ]
            )
            ->andWhere(
            [
                'user_id' => \Yii::$app->user->id,
            ]
            )
            ->innerJoinWith([
                'order' => function ($query) {
                    $query->andWhere(['orders.status' => Orders::STATUS_PAYED]);
                }
            ])
            ->addGroupBy('order_id')
            ->orderBy('order_id DESC')
        ;
        $orderList = $orderListQuuery->all();
        $totalStat = [];
        foreach ($orderList as $order) {
            $totalStat['price'] += $order->price;
            $totalStat['amount'] += $order->amount;
            $totalStat['weight'] += $order->weight;
            $totalStat['protein'] += $order->protein;
            $totalStat['fat'] += $order->fat;
            $totalStat['carbon'] += $order->carbon;
            $totalStat['kcal'] += $order->kcal;
        }

        $dataProvider = new ActiveDataProvider(
            [
                'query' => $orderListQuuery,
                'pagination' => [
                    'pageSize' => 100
                ],
                'sort' => false,
            ]
        );

        return $this->render('personal',
            [
                'statByOrderProvider' => $dataProvider,
                'totalStat' => $totalStat
            ]
        );
    }
}

views/orders/list.php
<?php
/* @var $this yii\web\View
 * @var $dataProvider \yii\data\ActiveDataProvider
 */

use app\models\Orders;
use app\widgets\Alert;
use yii\grid\GridView;
use yii\helpers\Html;


$this->title = 'Список заказов';
//$this->params['breadcrumbs'][] = $this->title;
?>
<div class="row">
    <div class="col-md-6">
        <h1><?= Html::encode($this->title) ?></h1>
    </div>
    <div class="col-md-6" style="margin-top: 20px;margin-bottom: 10px;">
        <a href="<?=\yii\helpers\Url::to(['statistics/personal'])?>" class="btn btn-primary" style="float: right">Персональная статистика</a>
    </div>
</div>

<?= Alert::widget() ?>
<?php

$columns = [
    [
        'attribute'=>'created_at',
        'label'=>'Заказы',
        'format'=>'date', // Доступные модификаторы - date:datetime:time
        'content'=>function($data) {
            $content = Html::a(
                    'Заказ №'.$data->id.' от ' . \Yii::$app->formatter->asDate($data->created_at, 'php:d.m.Y'),
                    \yii\helpers\Url::to(['orders/view', 'id' => $data->id])
            );

            return $content;
        }
    ],
    [
        'attribute'=>'is_today',
        'label'=>'Статус',
        'content'=>function($data) {
            $adminContent = '';
            /** @var Orders $data */
            if ($data->status == Orders::STATUS_ACTIVE) {
                $content = 'В процессе..';
                if (!$data->isProcessing()) {
                    $adminContent = '&nbsp;&nbsp;'.Html::a(
                            '<span class="glyphicon glyphicon-ok"></span>',
                            \yii\helpers\Url::to(['orders/block', 'id' => $data->id]),
                            ['title' => 'Заблокировать заказ']
                        );
                }

            }
            elseif (in_array($data->status, Orders::statusDone(), true)) {

                switch ($data->status) {
                    case Orders::STATUS_BLOCK:
                        $content = 'Заблокирован';
                        break;
                    default:
                    case Orders::STATUS_PAYED:
                        $content = 'Завершён';
                        break;
                }

                $adminContent = '&nbsp;&nbsp;' . Html::a(
                        '<span class="glyphicon glyphicon-eye-open"></span>',
                        \yii\helpers\Url::to(['orders/open', 'id' => $data->id]),
                        ['title' => 'Открыть заказ']
                    );

                if ($data->status !== Orders::STATUS_PAYED) {
                    $adminContent .= '&nbsp;&nbsp;' . Html::a(
                            '<span class="glyphicon glyphicon-ruble"></span>',
                            \yii\helpers\Url::to(['orders/pay-order', 'id' => $data->id]),
                            ['title' => 'Снять средства с балансов']
                        );
                }
            }

            if(!Yii::$app->user->isGuest && Yii::$app->user->identity->isAdmin()) {
                $content .= $adminContent;
            }
            return $content;
        }
    ],
];

$adminButton = '';
if(!Yii::$app->user->isGuest && Yii::$app->user->identity->isAdmin()) {
    $columns[] = [
        'class' => 'yii\grid\ActionColumn',
        'template' => '{delete}',
        'buttons' => [
            'delete' => function ($url,$model, $key) {
                return Html::a(
                    '<span class="glyphicon glyphicon-eye-close"></span>',
                    $url,
                    ['title' => 'Скрыть заказ']
                );
            },
        ],
    ];

    $adminButton = '<span class="glyphicon glyphicon-plus-sign"></span> ' .
        Html::a('Создать новый заказ', \yii\helpers\Url::to(['orders/add']));
}


echo GridView::widget([
    'dataProvider' => $dataProvider,
    'columns' => $columns,
    'pager' => [
        'hideOnSinglePage' => true,
    ],
    'layout'=>"{items}\n{pager}"
]);

echo $adminButton;

views/orders/view.php
<?php
/*
 * @var $this yii\web\View
 * @var $order app\models\Orders
 */

use app\models\OrderPositions;
use app\models\Orders;
use app\models\Tools;
use app\widgets\Alert;
use yii\grid\GridView;
use yii\helpers\Html;
use yii\widgets\Pjax;

$this->registerCssFile('@web/css/style-75.css');
?>
<h1>Заказ № <?=$order->id?> от <?=\Yii::$app->formatter->asDate($order->created_at, 'php:d.m.Y')?></h1>

<?php

$isAdmin = !Yii::$app->user->isGuest && Yii::$app->user->identity->isAdmin();

if ($order->status === Orders::STATUS_BLOCK) {
    echo '<p class="text-danger">Заказ заблокирован!</p>';
}

$columns = [
    [
        'attribute'=>'kdv_url',
        'label'=>'Товар',
        'content'=>function($data) {
            $content = Html::a(
                $data->caption?:$data->kdv_url,
                \yii\helpers\Url::to([$data->kdv_url], '')
            );
            if ($data->user_id === Yii::$app->user->id) {
                $content = '<b>' . $content . '</b>';
            }
            return $content;
        },
        'footer' => '<b>Итого:</b>',
    ],
    [
        'attribute'=>'weight',
        'label'=>'Вес, г.',
        'content'=>function($data) {
            $content = $data->weight;
            if ($data->user_id === Yii::$app->user->id) {
                $content = '<b>' . $content . '</b>';
            }
            return $content;
        },
        'footer' => "<b>" . OrderPositions::getDischangeHTML(OrderPositions::getTotalWeight($viewTotalPositionsList->models)) . "</b>",
    ],
    [
        'attribute'=>'amount',
        'label'=>'Кол-во',
        'content'=>function($data) {
            $content = $data->amount;
            if ($data->user_id === Yii::$app->user->id) {
                $content = '<b>' . $content . '</b>';
            }
            return $content;
        },
        'footer' => "<b>" . Tools::pageTotal($viewTotalPositionsList->models, 'amount') . "</b>",
    ],
    [
        'attribute'=>'price',
        'label'=>'Цена',
        'content'=>function($data) {
            $content = Tools::priceFormat($data->price);
            if ($data->user_id === Yii::$app->user->id) {
                $content = '<b>' . $content. '</b>';
            }
            return $content;
        },
    ],
    [
        'attribute' => 'total',
        'label' => 'Сумма',
        'content' => function ($data) {
            $content = Tools::priceFormat($data->amount * $data->price);
            if ($data->user_id === Yii::$app->user->id) {
                $content = '<b>' . $content . '</b>';
            }
            return $content;
        },
        'footer' => "<b>" . OrderPositions::getTotalPrice($viewTotalPositionsList->models) . "</b>",
    ],
    [
        'attribute' => 'user_id',
        'label' => 'Пользователь',
        'content'=>function($data) use($users) {
            $content = $users[$data->user_id];
            if ($data->user_id === Yii::$app->user->id) {
                $content = '<b>' . $content . '</b>';
            }
            return $content;
        },
        'filter' => $users
    ]
];

if($isAdmin) {
    $columns[] = [
        'attribute'=>'price',
        'label'=>'Цена КДВ',
        'content'=>function($data) {
            $content = Tools::priceFormat($data->kdv_price);
            if ($data->user_id === Yii::$app->user->id) {
                $content = '<b>' . $content . '</b>';
            }
            return $content;
        },
    ];
    $columns[] = [
        'attribute' => 'total',
        'label' => 'Сумма КДВ',
        'content' => function ($data) {
            $content = Tools::priceFormat($data->amount * $data->kdv_price);
            if ($data->user_id === Yii::$app->user->id) {
                $content = '<b>' . $content . '</b>';
            }
            return $content;
        },
        'footer' => "<b>" . OrderPositions::getTotalPrice($viewTotalPositionsList->models, true) . "</b>",
    ];
    $columns[] = [
        'class' => 'yii\grid\ActionColumn',
        'template' => '{delete}',
        'buttons' => [
            'delete' => function ($url,$model, $key) {
                return Html::a(
                    '<span class="glyphicon glyphicon-trash"></span>',
                    \yii\helpers\Url::to(['positions/delete', 'id' => $model->id, 'orderId' => $model->order_id]),
                    [
                        'data-pjax' => '#model-grid',
                        'title' => Yii::t('app', 'Delete')
                    ]
                );
            },
        ],
    ];

    if($order->status == Orders::STATUS_BLOCK) {
        $form = \yii\bootstrap\ActiveForm::begin([
            'layout' => 'inline',
            'id' => 'PositionsUpdateForm',
        ]);
        ?>
        <?= Alert::widget() ?>

        <?= $form->field($positionModel, 'kdv_url')->textInput(['placeholder' => "Kdv url"])->label(false);?>&nbsp;
        <?= $form->field($positionModel, 'amount')->textInput(['placeholder' => "Общее кол-во", 'value' => '1', 'type' => 'number'])->label(false)?>&nbsp;
        <?= $form->field($positionModel, 'user_id')->dropDownList($users)->label(Yii::t('app', 'Пользователь'))?>&nbsp;
        <button type="submit" class="btn btn-default">Добавить/изменить товар</button>
        <?php
        \yii\bootstrap\ActiveForm::end();
        echo '<br><br>';
    }
}
Pjax::begin([
    'clientOptions' => ['method' => 'POST']
]);
echo GridView::widget([
    'dataProvider' => $viewTotalPositionsList,
    'filterModel' => $searchModel,
    'columns' => $columns,
    'pager' => [
        'hideOnSinglePage' => true,
    ],
    'layout'=>"{items}\n{pager}",
    'showFooter' => true,
    'summary' => false,
]);
Pjax::end();
?>
<?if ($order->status == Orders::STATUS_PAYED) :?>
<h2>Доска почёта по заказу</h2>
<div class="row ui-75">
    <div class="col-md-4 col-sm-6 col-xs-6 col-mob">
        <div class="ui-item">
            <div class="bg-yellow text-center">
                <h2>Коллекционеры</h2>
                <small>Больше всех заказали единиц товара</small>
            </div>
            <ul class="clearfix">
                <?php foreach ($countPositionsList as $key => $countPositions):?>
                    <li>
                        <?=$users[$countPositions['user_id']]?>
                        <span><?=$countPositions['count_pos']?> шт.</span>
                    </li>
                <?php endforeach;?>
            </ul>
        </div>
    </div>
    <div class="col-md-4 col-sm-6 col-xs-6 col-mob">
        <div class="ui-item">
            <div class="bg-brown text-center">
                <h2>Тяжеловесы</h2>
                <small>Больше всех заказали по весу</small>
            </div>
            <ul class="clearfix">
                <?php foreach ($weightList as $key => $weight):?>
                    <li>
                        <?=$users[$weight['user_id']]?>
                        <span><?=OrderPositions::getDischangeHTML($weight['count_pos']/1000, 3)?> кг.</span>
                    </li>
                <?php endforeach;?>
            </ul>
        </div>
    </div>
    <div class="col-md-4 col-sm-6 col-xs-6 col-mob">
        <div class="ui-item">
            <div class="bg-green text-center">
                <h2>Транжиры</h2>
                <small>Потратил больше всех на заказ</small>
            </div>
            <ul class="clearfix">
                <?php foreach ($writeOffList as $key => $writeOff):?>
                    <li>
                        <?=$users[$writeOff['user_id']]?>
                        <span><?=OrderPositions::getDischangeHTML($writeOff['sum'], 2)?> р.</span>
                    </li>
                <?php endforeach;?>
            </ul>
        </div>
    </div>
</div>
<?endif;?>